### ISSUE TITLE
Update Documentation Template

### ISSUE THREAD

**Issue by bpalaggi** [bosagora/docs-bosagora-io#13]
As a Developer building on Agora, I need easily accessible platform documentation, so I can start building on Agora quickly.

Acceptance Criteria:
- [x] A modern looking theme similar to what other projects are using (theme can either be an existing solution or custom)
- [x] A section for Agora releases with changelogs. Similar to this: https://squidfunk.github.io/mkdocs-material/changelog/
- [x] Move Home, New to bosagora, learn, and releases to a toolbar on top
- [x] Make the documentation homepage look like the [SquidFunk homepage](https://squidfunk.github.io/mkdocs-material/)
- [x] Rename Full Node => Node

Example of what our end product COULD look like: https://docs.cardano.org/introduction/

**Comment by kchulj** [comment]
I will try with the [Material for MkDocs](https://squidfunk.github.io/mkdocs-material/getting-started/) theme.
Open to ideas.

**Comment by kchulj** [comment]
The change are initially reflected in the [mkdocs](https://github.com/bosagora/docs-bosagora-io/tree/mkdocs) branch, before merging into v0.x.x.

**Comment by kchulj** [comment]
Solved by #16 #17 #18 #19
