### ISSUE TITLE
Reformat Repository to Resolve Template Problems

### ISSUE THREAD

**Issue by bpalaggi** [bosagora/docs-bosagora-io#6]
As a user I need to be able to view the documentation page with the table of contents and have the selected content appear in order to gain a deeper understand of the Agora platform.

Documentation link: https://bosagora-documentation.readthedocs.io/en/latest/

**Need to have:**

- We need to reformat the current repository for user readability and usability
- Can we format it to support MD? (most likely possible)
- Need to fix formatting so the table of contents is displayed on the left-hand side
- Once an article is selected the body copy needs to be displayed in the middle of the page

**Example of what our MVP needs look like:** http://docs.annotatorjs.org/en/v1.2.x/

**Nice to have:**

- A modern looking theme similar to what other projects are using (theme can either be an existing solution or custom)
- A section for Agora releases with changelogs. Similar to this: https://squidfunk.github.io/mkdocs-material/changelog/

**Example of what our end product needs to look like:** https://docs.cardano.org/introduction/

**Comment by kchulj** [comment]
Reopening to reference the **Nice to have** section in the future.

**Comment by kchulj** [comment]
[MkDocs](https://www.mkdocs.org/user-guide/choosing-your-theme/) is one of the options for a more modern theme.
